name: Update Rules
on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Prepare
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          python -m pip install requests

      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import re
            import requests

            raw_url = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_AdblockPlus.ini"
            response = requests.get(raw_url)
            if response.status_code == 200:
                ini_content = response.text
                raw_lines = ini_content.splitlines()
                urls = []
                url_pattern = re.compile(r'(https?://[^\s]+)')
                for line in raw_lines:
                    if line.startswith("ruleset") and "http" in line:
                        match = url_pattern.search(line)
                        if match:
                            url = match.group(0)
                            fix_url = url.replace("master/Clash", "master/Clash/Providers").replace(".list", ".yaml")
                            urls.append(fix_url)

                def download_file(url: str, save_path):
                    response = requests.get(url)
                    if response.status_code == 200:
                        with open(save_path, 'wb') as file:
                            file.write(response.content)
                    else:
                        newurl = url.replace("Providers","Providers/Ruleset")
                        response = requests.get(newurl)
                        if response.status_code == 200:
                            with open(save_path, 'wb') as file:
                                file.write(response.content)
                        else:
                            print(f"download fail {url}")
                if not os.path.exists("publish"):
                    os.mkdir("publish")
                for url in urls:
                    file_path = os.path.join("publish", os.path.basename(url))
                    download_file(url, file_path)

      - name: Git push assets to "release" branch
        run: |
          cd publish
          git init
          git config --local user.name "actions"
          git config --local user.email "action@github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release
